import { SystemRole } from '@fapoms/shared';

/**
 * Which permissions each role holds — the one table, in one place.
 *
 * Two things decide who may call a route: `@Roles(...)`, which names the audience and denies
 * anything it does not name, and `@RequirePermissions('resource:action:scope')`, which the
 * PermissionsGuard resolves against the grants below. Both must pass. So a role named by
 * `@Roles` but missing the route's permission is refused — while the code says it is allowed.
 *
 * That is what had happened. Twenty-four routes named a role that could not call them:
 * an OPERATIONS_MANAGER could not create a branch, run the planner, edit the holiday calendar
 * or add a zone; an ADMINISTRATOR could not create or edit an organisation; a DATA_ENTRY_HEAD
 * could not open a validation case. Worse, the `OCR` permissions did not exist as rows at all,
 * so the three OCR boundary routes were refused to every principal including the super
 * administrator — the same failure the holiday calendar hit once before, noted in a comment
 * there and never generalised.
 *
 * None of it was visible: the guard's refusal is indistinguishable from a role genuinely not
 * being allowed, and the grants lived partly in the seed and partly across a chain of
 * migrations, so no single place could be read to find out what a role actually held.
 *
 * This is now that place. The seed builds roles from it, a migration reconciles existing
 * deployments to it, and `route-permission-parity.spec.ts` fails if any route's `@Roles`
 * names a role this table does not grant the route's permission to.
 *
 * A grant with scope PLATFORM implies every narrower scope — see PermissionsGuard.
 */
export const ROLE_PERMISSIONS: Record<SystemRole, string[]> = {
  [SystemRole.SUPER_ADMINISTRATOR]: [
    'ASSAYER:CREATE:ORGANIZATION',
    'ASSAYER:DELETE:ORGANIZATION',
    'ASSAYER:EDIT:ORGANIZATION',
    'ASSAYER:VIEW:PLATFORM',
    'ASSIGNMENT:ACCEPT:SELF',
    'ASSIGNMENT:CANCEL:ORGANIZATION',
    'ASSIGNMENT:CREATE:ORGANIZATION',
    'ASSIGNMENT:NEGOTIATE:ORGANIZATION',
    'ASSIGNMENT:VIEW:ASSIGNED_RECORDS',
    'ASSIGNMENT:VIEW:PLATFORM',
    'AUDIT_LOG:VIEW:PLATFORM',
    'BILLING:APPROVE:ORGANIZATION',
    'BILLING:CREATE:ORGANIZATION',
    'BILLING:EDIT:ORGANIZATION',
    'BILLING:VIEW:PLATFORM',
    'BRANCH:CREATE:ORGANIZATION',
    'BRANCH:DELETE:ORGANIZATION',
    'BRANCH:EDIT:ORGANIZATION',
    'BRANCH:IMPORT:ORGANIZATION',
    'BRANCH:VIEW:PLATFORM',
    'CLIENT:CREATE:ORGANIZATION',
    'CLIENT:DELETE:ORGANIZATION',
    'CLIENT:EDIT:ORGANIZATION',
    'CLIENT:VIEW:PLATFORM',
    'CONFIGURATION:EDIT:PLATFORM',
    'CONFIGURATION:VIEW:PLATFORM',
    'DOCUMENT:CREATE:ORGANIZATION',
    'DOCUMENT:DOWNLOAD:PLATFORM',
    'DOCUMENT:EDIT:ORGANIZATION',
    'DOCUMENT:GENERATE:ORGANIZATION',
    'DOCUMENT:UPLOAD:ORGANIZATION',
    'DOCUMENT:VIEW:PLATFORM',
    'OCR:CREATE:ORGANIZATION',
    'OCR:EDIT:ORGANIZATION',
    'ORGANIZATION:CREATE:ORGANIZATION',
    'ORGANIZATION:DELETE:ORGANIZATION',
    'ORGANIZATION:EDIT:ORGANIZATION',
    'PLANNING:CREATE:ORGANIZATION',
    'PLANNING:DELETE:ORGANIZATION',
    'PLANNING:EDIT:ORGANIZATION',
    'PLANNING:VIEW:PLATFORM',
    'PROJECT:ARCHIVE:ORGANIZATION',
    'PROJECT:CLOSE:ORGANIZATION',
    'PROJECT:CREATE:ORGANIZATION',
    'PROJECT:DELETE:ORGANIZATION',
    'PROJECT:EDIT:ORGANIZATION',
    'PROJECT:VIEW:PLATFORM',
    'REFERENCE_DATA:CREATE:ORGANIZATION',
    'REFERENCE_DATA:DELETE:ORGANIZATION',
    'REFERENCE_DATA:EDIT:ORGANIZATION',
    'REFERENCE_DATA:VIEW:PLATFORM',
    'SCHEDULING:CREATE:ORGANIZATION',
    'SCHEDULING:MODIFY:ORGANIZATION',
    'SCHEDULING:VIEW:PLATFORM',
    'USER:CREATE:PLATFORM',
    'USER:EDIT:PLATFORM',
    'USER:VIEW:PLATFORM',
    'VALIDATION:APPROVE:ORGANIZATION',
    'VALIDATION:ASSIGN:ORGANIZATION',
    'VALIDATION:CREATE:ORGANIZATION',
    'VALIDATION:EDIT:ORGANIZATION',
    'VALIDATION:REVIEW:ASSIGNED_RECORDS',
    'VALIDATION:VIEW:PLATFORM',
  ],

  [SystemRole.ADMINISTRATOR]: [
    'ASSAYER:CREATE:ORGANIZATION',
    'ASSAYER:DELETE:ORGANIZATION',
    'ASSAYER:EDIT:ORGANIZATION',
    'ASSAYER:VIEW:PLATFORM',
    'ASSIGNMENT:CANCEL:ORGANIZATION',
    'ASSIGNMENT:CREATE:ORGANIZATION',
    'ASSIGNMENT:NEGOTIATE:ORGANIZATION',
    'ASSIGNMENT:VIEW:PLATFORM',
    'AUDIT_LOG:VIEW:PLATFORM',
    'BILLING:APPROVE:ORGANIZATION',
    'BILLING:CREATE:ORGANIZATION',
    'BILLING:EDIT:ORGANIZATION',
    'BILLING:VIEW:PLATFORM',
    'BRANCH:CREATE:ORGANIZATION',
    'BRANCH:DELETE:ORGANIZATION',
    'BRANCH:EDIT:ORGANIZATION',
    'BRANCH:IMPORT:ORGANIZATION',
    'BRANCH:VIEW:PLATFORM',
    'CLIENT:CREATE:ORGANIZATION',
    'CLIENT:DELETE:ORGANIZATION',
    'CLIENT:EDIT:ORGANIZATION',
    'CLIENT:VIEW:PLATFORM',
    'CONFIGURATION:VIEW:PLATFORM',
    'DOCUMENT:CREATE:ORGANIZATION',
    'DOCUMENT:DOWNLOAD:PLATFORM',
    'DOCUMENT:EDIT:ORGANIZATION',
    'DOCUMENT:GENERATE:ORGANIZATION',
    'DOCUMENT:UPLOAD:ORGANIZATION',
    'DOCUMENT:VIEW:PLATFORM',
    'OCR:CREATE:ORGANIZATION',
    'OCR:EDIT:ORGANIZATION',
    'ORGANIZATION:CREATE:ORGANIZATION',
    'ORGANIZATION:DELETE:ORGANIZATION',
    'ORGANIZATION:EDIT:ORGANIZATION',
    'PLANNING:CREATE:ORGANIZATION',
    'PLANNING:DELETE:ORGANIZATION',
    'PLANNING:EDIT:ORGANIZATION',
    'PLANNING:VIEW:PLATFORM',
    'PROJECT:ARCHIVE:ORGANIZATION',
    'PROJECT:CLOSE:ORGANIZATION',
    'PROJECT:CREATE:ORGANIZATION',
    'PROJECT:DELETE:ORGANIZATION',
    'PROJECT:EDIT:ORGANIZATION',
    'PROJECT:VIEW:PLATFORM',
    'REFERENCE_DATA:CREATE:ORGANIZATION',
    'REFERENCE_DATA:DELETE:ORGANIZATION',
    'REFERENCE_DATA:EDIT:ORGANIZATION',
    'REFERENCE_DATA:VIEW:PLATFORM',
    'SCHEDULING:CREATE:ORGANIZATION',
    'SCHEDULING:MODIFY:ORGANIZATION',
    'SCHEDULING:VIEW:PLATFORM',
    'USER:CREATE:PLATFORM',
    'USER:EDIT:PLATFORM',
    'USER:VIEW:PLATFORM',
    'VALIDATION:APPROVE:ORGANIZATION',
    'VALIDATION:ASSIGN:ORGANIZATION',
    'VALIDATION:CREATE:ORGANIZATION',
    'VALIDATION:EDIT:ORGANIZATION',
    'VALIDATION:VIEW:PLATFORM',
  ],

  [SystemRole.OPERATIONS_MANAGER]: [
    'ASSIGNMENT:CANCEL:ORGANIZATION',
    'ASSIGNMENT:CREATE:ORGANIZATION',
    'ASSIGNMENT:NEGOTIATE:ORGANIZATION',
    'ASSIGNMENT:VIEW:PLATFORM',
    'BRANCH:CREATE:ORGANIZATION',
    'BRANCH:EDIT:ORGANIZATION',
    'BRANCH:IMPORT:ORGANIZATION',
    'BRANCH:VIEW:PLATFORM',
    'CLIENT:CREATE:ORGANIZATION',
    'CLIENT:EDIT:ORGANIZATION',
    'CLIENT:VIEW:PLATFORM',
    'DOCUMENT:CREATE:ORGANIZATION',
    'DOCUMENT:DOWNLOAD:PLATFORM',
    'DOCUMENT:GENERATE:ORGANIZATION',
    'DOCUMENT:UPLOAD:ORGANIZATION',
    'PLANNING:CREATE:ORGANIZATION',
    'PLANNING:EDIT:ORGANIZATION',
    'PROJECT:ARCHIVE:ORGANIZATION',
    'PROJECT:CLOSE:ORGANIZATION',
    'PROJECT:CREATE:ORGANIZATION',
    'PROJECT:DELETE:ORGANIZATION',
    'PROJECT:EDIT:ORGANIZATION',
    'PROJECT:VIEW:PLATFORM',
    'REFERENCE_DATA:CREATE:ORGANIZATION',
    'REFERENCE_DATA:DELETE:ORGANIZATION',
    'REFERENCE_DATA:EDIT:ORGANIZATION',
    'SCHEDULING:CREATE:ORGANIZATION',
    'SCHEDULING:MODIFY:ORGANIZATION',
    'SCHEDULING:VIEW:PLATFORM',
  ],

  [SystemRole.OPERATIONS_EXECUTIVE]: [
    'ASSIGNMENT:NEGOTIATE:ORGANIZATION',
    'ASSIGNMENT:VIEW:PLATFORM',
    'BRANCH:VIEW:PLATFORM',
    'DOCUMENT:DOWNLOAD:PLATFORM',
    'PROJECT:VIEW:PLATFORM',
    'SCHEDULING:CREATE:ORGANIZATION',
    'SCHEDULING:MODIFY:ORGANIZATION',
    'SCHEDULING:VIEW:PLATFORM',
  ],

  [SystemRole.VALIDATION_MANAGER]: [
    'ASSIGNMENT:VIEW:PLATFORM',
    'BRANCH:VIEW:PLATFORM',
    'DOCUMENT:DOWNLOAD:PLATFORM',
    'DOCUMENT:EDIT:ORGANIZATION',
    'PROJECT:VIEW:PLATFORM',
    'VALIDATION:CREATE:ORGANIZATION',
    'VALIDATION:EDIT:ORGANIZATION',
  ],

  [SystemRole.VALIDATOR]: [
    'DOCUMENT:DOWNLOAD:PLATFORM',
    'PROJECT:VIEW:PLATFORM',
    'VALIDATION:REVIEW:ASSIGNED_RECORDS',
  ],

  [SystemRole.DATA_ENTRY_HEAD]: [
    'ASSIGNMENT:VIEW:PLATFORM',
    'BRANCH:VIEW:PLATFORM',
    'DOCUMENT:DOWNLOAD:PLATFORM',
    'DOCUMENT:EDIT:ORGANIZATION',
    'PROJECT:VIEW:PLATFORM',
    'VALIDATION:CREATE:ORGANIZATION',
  ],

  [SystemRole.DOCUMENT_EXECUTIVE]: [
    'ASSIGNMENT:VIEW:PLATFORM',
    'BRANCH:VIEW:PLATFORM',
    'DOCUMENT:CREATE:ORGANIZATION',
    'DOCUMENT:DOWNLOAD:PLATFORM',
    'DOCUMENT:EDIT:ORGANIZATION',
    'DOCUMENT:GENERATE:ORGANIZATION',
    'DOCUMENT:UPLOAD:ORGANIZATION',
    'OCR:EDIT:ORGANIZATION',
    'PROJECT:VIEW:PLATFORM',
    'SCHEDULING:VIEW:PLATFORM',
  ],

  [SystemRole.FINANCE_MANAGER]: [
    'BILLING:APPROVE:ORGANIZATION',
    'BILLING:CREATE:ORGANIZATION',
    'BILLING:EDIT:ORGANIZATION',
    'BILLING:VIEW:PLATFORM',
  ],

  [SystemRole.HR_MANAGER]: [
    'ASSAYER:CREATE:ORGANIZATION',
    'ASSAYER:DELETE:ORGANIZATION',
    'ASSAYER:EDIT:ORGANIZATION',
    'ASSIGNMENT:VIEW:PLATFORM',
    'BRANCH:VIEW:PLATFORM',
    'PLANNING:VIEW:PLATFORM',
    'PROJECT:VIEW:PLATFORM',
    'SCHEDULING:VIEW:PLATFORM',
  ],

  [SystemRole.READ_ONLY_AUDITOR]: [
    'ASSIGNMENT:VIEW:PLATFORM',
    'AUDIT_LOG:VIEW:PLATFORM',
    'BILLING:VIEW:PLATFORM',
    'BRANCH:VIEW:PLATFORM',
    'CLIENT:VIEW:PLATFORM',
    'PLANNING:VIEW:PLATFORM',
    'PROJECT:VIEW:PLATFORM',
    'SCHEDULING:VIEW:PLATFORM',
  ],

  [SystemRole.CLIENT_USER]: [
    'BRANCH:VIEW:PLATFORM',
    'PROJECT:VIEW:PLATFORM',
    'SCHEDULING:VIEW:PLATFORM',
  ],

  /**
   * No permission grants.
   *
   * Every route this role reaches is gated by `@Roles` alone; none of them also asks for a
   * permission, so an empty list here denies nothing. Listed explicitly so that the absence
   * reads as a decision rather than an omission.
   */
  [SystemRole.PRODUCT_SUPPORT]: [],

  /**
   * The field assayer holds no permission grants, and cannot.
   *
   * An assayer is authenticated from the `assayers` table and has no row in `roles`, so the
   * PermissionsGuard resolves nothing for them. Every route an assayer reaches is therefore
   * gated by `@Roles` alone — and any route that paired `SystemRole.ASSAYER` with a permission
   * would refuse them outright. The parity spec fails on exactly that pairing.
   */
  [SystemRole.ASSAYER]: [],
};

/** Every permission any role is granted — what the `permissions` table must contain. */
export const ALL_GRANTED_PERMISSIONS: string[] = [
  ...new Set(Object.values(ROLE_PERMISSIONS).flat()),
].sort();
