#!/usr/bin/env bash
# =============================================================================
# FAPOMS - on-box application bootstrap (run on the EC2 instance via SSM).
#
# The CloudFormation stack builds the infrastructure and leaves Docker ready.
# This brings the APPLICATION up: fetches the code, writes a COMPLETE production
# env (secrets generated, external integrations left as clearly-marked blanks),
# points object storage at S3 via the instance role (no keys on the box),
# configures LiveKit for the public IP, and starts the stack.
#
# In 'full' mode it ALSO self-hosts ClamAV + Nominatim + OSRM and wires them in.
#
# Re-runnable. Set the values at the top (or export them), then run:
#   sudo -i
#   export PUBLIC_IP=<Elastic IP>  S3_BUCKET=<bucket>  AWS_REGION=ap-south-1
#   export MODE=saving                                   # or: full
#   export GIT_URL="https://<token>@github.com/<you>/gssAutomation.git"   # or pre-place code
#   bash bootstrap.sh
# =============================================================================
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/fapoms}"
OSM_DATA_DIR="${OSM_DATA_DIR:-/opt/fapoms-osm}"
MODE="${MODE:-saving}"
PUBLIC_IP="${PUBLIC_IP:?set PUBLIC_IP to the Elastic IP from the stack output}"
S3_BUCKET="${S3_BUCKET:?set S3_BUCKET to the bucket name from the stack output}"
AWS_REGION="${AWS_REGION:-ap-south-1}"
GIT_URL="${GIT_URL:-}"
export OSM_DATA_DIR   # used by the full overlay compose file

case "$MODE" in saving|full) ;; *) echo "MODE must be 'saving' or 'full'"; exit 2 ;; esac
echo "==> FAPOMS bootstrap  [mode=$MODE, host=$PUBLIC_IP, bucket=$S3_BUCKET, region=$AWS_REGION]"

# --- 1. Code --------------------------------------------------------------
if [ ! -d "$APP_DIR/.git" ] && [ ! -f "$APP_DIR/deploy/docker-compose.prod.yml" ]; then
  if [ -n "$GIT_URL" ]; then git clone "$GIT_URL" "$APP_DIR"
  else echo "!! No code at $APP_DIR and no GIT_URL. Clone with a token, or copy the repo there."; exit 1; fi
fi
cd "$APP_DIR"

# --- 2. Secrets + complete env (generated once; re-runs keep them) ---------
# Postgres data and PII ciphertext persist, so DB_PASSWORD and PII_ENCRYPTION_KEY
# must NOT change after first run or existing data becomes unreadable.
ENV_FILE="$APP_DIR/.env.docker"
gen() { tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-32}"; }

if [ -f "$ENV_FILE" ] && grep -q '^DB_PASSWORD=' "$ENV_FILE"; then
  echo "==> keeping existing $ENV_FILE"
  # shellcheck disable=SC1090
  set -a; . "$ENV_FILE"; set +a
else
  echo "==> writing a complete $ENV_FILE"
  DB_PASSWORD="$(gen 32)"; JWT_SECRET="$(gen 48)"
  PII_ENCRYPTION_KEY="$(gen 64)"; DOCUMENT_TOKEN_SECRET="$(gen 48)"
  LIVEKIT_API_KEY="APl$(gen 12)"; LIVEKIT_API_SECRET="$(gen 48)"
  BULL_BOARD_PASSWORD="$(gen 20)"; NOMINATIM_PASSWORD="$(gen 20)"

  if [ "$MODE" = "full" ]; then
    SCAN_REQUIRED=true; CLAMAV_LINE="CLAMAV_HOST=clamav"; CLAMAV_PORT_LINE="CLAMAV_PORT=3310"
    NOMINATIM_LINE="NOMINATIM_URL=http://nominatim:8080"; OSRM_LINE="OSRM_URL=http://osrm:5000"
  else
    SCAN_REQUIRED=false; CLAMAV_LINE="# CLAMAV_HOST=          # set to enable upload virus scanning"
    CLAMAV_PORT_LINE="# CLAMAV_PORT=3310"
    NOMINATIM_LINE="# NOMINATIM_URL=        # point at your geocoder, or a hosted API"
    OSRM_LINE="# OSRM_URL=              # point at your router, or a hosted API"
  fi

  cat > "$ENV_FILE" <<EOF
# --- Generated by deploy/aws/bootstrap.sh (mode=$MODE). Contains secrets - never commit. ---
NODE_ENV=production
PORT=3000
TRUST_PROXY=true

# Database (self-hosted)
DB_HOST=postgres
DB_PORT=5432
DB_USERNAME=fapoms
DB_PASSWORD=${DB_PASSWORD}
DB_DATABASE=fapoms
DB_SYNCHRONIZE=false

# Redis (self-hosted)
REDIS_HOST=redis
REDIS_PORT=6379

# Object storage: real S3. No S3_ENDPOINT / no path-style => regional S3 endpoint,
# and the AWS SDK reads credentials from the EC2 instance role. No keys on the box.
STORAGE_DRIVER=s3
S3_BUCKET_NAME=${S3_BUCKET}
AWS_REGION=${AWS_REGION}
AWS_DEFAULT_REGION=${AWS_REGION}
S3_FORCE_PATH_STYLE=false

# Public URLs - HTTP on the Elastic IP until you add a domain + HTTPS.
FRONTEND_URL=http://${PUBLIC_IP}
APP_PUBLIC_URL=http://${PUBLIC_IP}
CORS_ORIGINS=http://${PUBLIC_IP}

# Secrets
JWT_SECRET=${JWT_SECRET}
PII_ENCRYPTION_KEY=${PII_ENCRYPTION_KEY}
DOCUMENT_TOKEN_SECRET=${DOCUMENT_TOKEN_SECRET}
BULL_BOARD_USER=admin
BULL_BOARD_PASSWORD=${BULL_BOARD_PASSWORD}

# LiveKit (self-hosted; keys must match infrastructure/livekit/livekit.yaml - written below)
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
LIVEKIT_HOST=http://livekit:7880
LIVEKIT_PUBLIC_URL=http://${PUBLIC_IP}:7880

# Upload virus scanning (ClamAV)
FILE_SCAN_REQUIRED=${SCAN_REQUIRED}
${CLAMAV_LINE}
${CLAMAV_PORT_LINE}

# Geocoder / router
${NOMINATIM_LINE}
${OSRM_LINE}
GEOCODER_USER_AGENT=FAPOMS/1.0
NOMINATIM_PASSWORD=${NOMINATIM_PASSWORD}

# ============ YOU MUST FILL THESE IN (per-account / external services) ============
# Google Maps (mobile map + backend geocoding fallback)
GOOGLE_MAPS_API_KEY=
# Push (Firebase FCM) - either place the service-account JSON next to the compose file,
# or set these three from it:
FCM_PROJECT_ID=
FCM_CLIENT_EMAIL=
FCM_PRIVATE_KEY=
# Email - use Amazon SES SMTP, or Gmail. Fill ONE set.
EMAIL_FROM=
SMTP_HOST=email-smtp.${AWS_REGION}.amazonaws.com
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASSWORD=
# GMAIL_USER=
# GMAIL_APP_PASSWORD=
# ==================================================================================
EOF
  chmod 600 "$ENV_FILE"
  set -a; . "$ENV_FILE"; set +a
fi

# --- 3. LiveKit config for the public IP ----------------------------------
LK="$APP_DIR/infrastructure/livekit/livekit.yaml"
if [ -f "$LK" ]; then
  echo "==> writing LiveKit config for public IP $PUBLIC_IP"
  cat > "$LK" <<EOF
port: 7880
rtc:
  port_range_start: 50100
  port_range_end: 50200
  tcp_port: 7881
  use_external_ip: true
  node_ip: ${PUBLIC_IP}
keys:
  ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
turn:
  enabled: true
  udp_port: 3478
  domain: ${PUBLIC_IP}
logging:
  level: info
EOF
fi

# --- 4. AWS base compose: prod minus MinIO (S3 replaces it) ----------------
AWS_COMPOSE="$APP_DIR/deploy/docker-compose.aws.yml"
python3 - "$APP_DIR/deploy/docker-compose.prod.yml" "$AWS_COMPOSE" <<'PY'
import sys, yaml
src, dst = sys.argv[1], sys.argv[2]
d = yaml.safe_load(open(src))
svcs = d.get("services", {})
svcs.pop("minio", None)
be = svcs.get("backend", {})
dep = be.get("depends_on")
if isinstance(dep, dict): dep.pop("minio", None)
elif isinstance(dep, list) and "minio" in dep: dep.remove("minio")
d.get("volumes", {}).pop("miniodata", None)
yaml.safe_dump(d, open(dst, "w"), sort_keys=False)
print(f"wrote {dst} (minio removed)")
PY

COMPOSE_FILES=(-f "$AWS_COMPOSE")

# --- 5. Full mode: prepare + include OSM/scanning services -----------------
if [ "$MODE" = "full" ]; then
  echo "==> full mode: preparing the OSRM road graph (India). This downloads ~1 GB and can take a while."
  PBF_URL="${NOMINATIM_PBF_URL:-https://download.geofabrik.de/asia/india-latest.osm.pbf}"
  mkdir -p "$OSM_DATA_DIR/osrm"; cd "$OSM_DATA_DIR/osrm"
  [ -f india-latest.osm.pbf ] || curl -fSL "$PBF_URL" -o india-latest.osm.pbf
  if [ ! -f india-latest.osrm.mldgr ]; then
    docker run --rm -v "$PWD:/data" osrm/osrm-backend osrm-extract   -p /opt/car.lua /data/india-latest.osm.pbf
    docker run --rm -v "$PWD:/data" osrm/osrm-backend osrm-partition /data/india-latest.osrm
    docker run --rm -v "$PWD:/data" osrm/osrm-backend osrm-customize /data/india-latest.osrm
  fi
  cd "$APP_DIR"
  COMPOSE_FILES+=(-f "$APP_DIR/deploy/aws/docker-compose.aws-full.yml")
  echo "==> Nominatim will import the India extract on first start (HOURS). It serves once done."
fi

# --- 6. Up ----------------------------------------------------------------
echo "==> starting the stack"
docker compose --env-file "$ENV_FILE" "${COMPOSE_FILES[@]}" up -d --build

echo ""
echo "==> up (mode=$MODE). Next:"
echo "   * Fill the 'YOU MUST FILL THESE IN' block in $ENV_FILE (Google Maps, FCM, email),"
echo "     then: docker compose --env-file $ENV_FILE ${COMPOSE_FILES[*]} up -d"
echo "   * Data:   deploy/restore.sh <pg_dump>   OR   docker compose ${COMPOSE_FILES[*]} exec backend npm run --workspace=packages/backend seed"
echo "   * Health: curl -s http://localhost:8080/api/v1/health"
echo "   * App:    http://${PUBLIC_IP}"
[ "$MODE" = "full" ] && echo "   * Nominatim import runs for hours; routing (OSRM) is ready now."
