import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1784653336579 implements MigrationInterface {
    name = 'InitialMigration1784653336579'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "client_code" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "display_name" character varying(255) NOT NULL, "contact_person" character varying(200), "contact_email" character varying(255), "contact_phone" character varying(20), "address" text, CONSTRAINT "UQ_7874e3c6cbb791a3bc75c9dcd71" UNIQUE ("client_code"), CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "zones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "name" character varying(150) NOT NULL, "description" text, "client_id" uuid, "states" jsonb, "districts" jsonb, CONSTRAINT "PK_880484a43ca311707b05895bd4a" PRIMARY KEY ("id")); COMMENT ON COLUMN "zones"."states" IS 'List of state codes grouped under this zone'; COMMENT ON COLUMN "zones"."districts" IS 'List of district names grouped under this zone'`);
        await queryRunner.query(`CREATE INDEX "IDX_fe93525d97616feb04ceec8765" ON "zones" ("client_id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "resource" character varying(50) NOT NULL, "action" character varying(50) NOT NULL, "scope" character varying(50) NOT NULL, "description" text, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id")); COMMENT ON COLUMN "permissions"."resource" IS 'Resource this permission applies to, e.g. PROJECT, ASSIGNMENT'; COMMENT ON COLUMN "permissions"."action" IS 'Action permitted, e.g. VIEW, CREATE, EDIT'; COMMENT ON COLUMN "permissions"."scope" IS 'Scope of the permission, e.g. SELF, ORGANIZATION, PLATFORM'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d577922d963695c90b61c67f3d" ON "permissions" ("resource", "action", "scope") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "name" character varying(50) NOT NULL, "display_name" character varying(100) NOT NULL, "description" text, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id")); COMMENT ON COLUMN "roles"."name" IS 'Machine-readable role identifier, e.g. OPERATIONS_MANAGER'`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "username" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "display_name" character varying(200) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "department_id" uuid, "phone" character varying(20), "last_login_at" TIMESTAMP WITH TIME ZONE, "failed_login_attempts" integer NOT NULL DEFAULT '0', "locked_until" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")); COMMENT ON COLUMN "users"."status" IS 'User status: INVITED, ACTIVE, SUSPENDED, LOCKED, DISABLED, ARCHIVED'`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "branch_code" character varying(50) NOT NULL, "sol_id" character varying(50), "name" character varying(255) NOT NULL, "address" text NOT NULL, "state" character varying(100) NOT NULL, "district" character varying(100) NOT NULL, "city" character varying(100) NOT NULL, "pincode" character varying(20), "latitude" numeric(10,7), "longitude" numeric(10,7), "location" geometry(Point,4326), "client_id" uuid, CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_42d97150eb00982d34c088749b" ON "branches" USING GiST ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_181a8cdaff4e1db94ff147163e" ON "branches" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed88203149dc0c61c57fc27da5" ON "branches" ("sol_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b48a680eb17f642cc36ff78d8" ON "branches" ("branch_code") `);
        await queryRunner.query(`CREATE TABLE "assayers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "assayer_code" character varying(50) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "display_name" character varying(200) NOT NULL, "email" character varying(255), "phone" character varying(20) NOT NULL, "alternate_phone" character varying(20), "address" text NOT NULL, "state" character varying(100) NOT NULL, "district" character varying(100) NOT NULL, "city" character varying(100) NOT NULL, "pincode" character varying(20), "latitude" numeric(10,7), "longitude" numeric(10,7), "location" geometry(Point,4326), "status" character varying(50) NOT NULL DEFAULT 'REGISTERED', "pan_number" character varying(20), "bank_account_number" character varying(50), "ifsc_code" character varying(20), "notes" text, CONSTRAINT "UQ_ac38fe8dfe44eb1ad3310e29fb0" UNIQUE ("assayer_code"), CONSTRAINT "PK_6ceb71d7ed721485307e436f847" PRIMARY KEY ("id")); COMMENT ON COLUMN "assayers"."status" IS 'Assayer status: REGISTERED, ACTIVE, INACTIVE, BUSY, SUSPENDED'`);
        await queryRunner.query(`CREATE INDEX "IDX_e12a47006c59a934a43a18565e" ON "assayers" USING GiST ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_0dff65957a13ec73746787b645" ON "assayers" ("state") `);
        await queryRunner.query(`CREATE INDEX "IDX_719f463c7996b212e17d1dbe65" ON "assayers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac38fe8dfe44eb1ad3310e29fb" ON "assayers" ("assayer_code") `);
        await queryRunner.query(`CREATE TYPE "public"."assignments_status_enum" AS ENUM('CREATED', 'CANDIDATE_SELECTED', 'CONTACT_INITIATED', 'NEGOTIATION', 'ACCEPTED', 'SCHEDULED', 'AUDIT_COMPLETED', 'CLOSED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "assignment_number" character varying(50) NOT NULL, "project_branch_id" uuid NOT NULL, "project_id" uuid NOT NULL, "assayer_id" uuid NOT NULL, "status" "public"."assignments_status_enum" NOT NULL DEFAULT 'CREATED', "proposed_fee" numeric(12,2), "agreed_fee" numeric(12,2), "scheduled_date" date, "completion_date" date, "remarks" text, "cancel_reason" text, "reject_reason" text, CONSTRAINT "UQ_7c08693fc11883cd6b712a1fed2" UNIQUE ("assignment_number"), CONSTRAINT "REL_66969a729f0c24ff71d5ba18c4" UNIQUE ("project_branch_id"), CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce6fc1fcaf3f268efa288ff5a7" ON "assignments" ("assayer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_18b8aab3ad95fc3377bb998688" ON "assignments" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_66969a729f0c24ff71d5ba18c4" ON "assignments" ("project_branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c08693fc11883cd6b712a1fed" ON "assignments" ("assignment_number") `);
        await queryRunner.query(`CREATE TYPE "public"."project_branches_status_enum" AS ENUM('IMPORTED', 'PLANNING', 'CANDIDATE_SEARCH', 'CONTACT_INITIATED', 'NEGOTIATION', 'ASSIGNMENT_CONFIRMED', 'SCHEDULED', 'AUDIT_COMPLETED', 'VALIDATION_COMPLETED', 'CLOSED', 'UNABLE_TO_COVER', 'ON_HOLD', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."project_branches_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "project_branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "project_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "status" "public"."project_branches_status_enum" NOT NULL DEFAULT 'IMPORTED', "priority" "public"."project_branches_priority_enum" NOT NULL DEFAULT 'MEDIUM', "zone_id" uuid, "scheduled_date" date, "remarks" text, CONSTRAINT "PK_896ad4a1bb6cbdda0857674194e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e536b9d53cc6c920bdbcb94d06" ON "project_branches" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d893541df1e35cef989cc4bed9" ON "project_branches" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_55cbe3e92921e38a60ccc2926e" ON "project_branches" ("project_id") `);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('DRAFT', 'PLANNING', 'SCHEDULING', 'EXECUTION', 'VALIDATION', 'COMPLETED', 'ARCHIVED', 'CANCELLED', 'ON_HOLD')`);
        await queryRunner.query(`CREATE TYPE "public"."projects_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "project_number" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "client_id" uuid NOT NULL, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'DRAFT', "priority" "public"."projects_priority_enum" NOT NULL DEFAULT 'MEDIUM', "start_date" date, "end_date" date, CONSTRAINT "UQ_a77b19582f25838ea68bbd4ffdf" UNIQUE ("project_number"), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca29f959102228649e71482747" ON "projects" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a77b19582f25838ea68bbd4ffd" ON "projects" ("project_number") `);
        await queryRunner.query(`CREATE TABLE "holidays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "name" character varying(150) NOT NULL, "date" date NOT NULL, "type" character varying(20) NOT NULL DEFAULT 'NATIONAL', "applicable_states" jsonb, "year" integer NOT NULL, CONSTRAINT "PK_3646bdd4c3817d954d830881dfe" PRIMARY KEY ("id")); COMMENT ON COLUMN "holidays"."type" IS 'Holiday type: NATIONAL, BANK, REGIONAL, CUSTOM'; COMMENT ON COLUMN "holidays"."applicable_states" IS 'List of state codes where this holiday is observed. Empty = nationwide.'`);
        await queryRunner.query(`CREATE INDEX "IDX_3c166450c737779ebaab2bf408" ON "holidays" ("year") `);
        await queryRunner.query(`CREATE INDEX "IDX_40dfddee0c0d7125c767d8962b" ON "holidays" ("date") `);
        await queryRunner.query(`CREATE TABLE "client_configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "client_id" uuid NOT NULL, "import_mapping" jsonb, "working_days" jsonb, "default_radius" numeric(5,2) NOT NULL DEFAULT '50', "sla_rules" jsonb, "effective_from" TIMESTAMP WITH TIME ZONE NOT NULL, "effective_to" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_8997ef77f905e17348c021608f" UNIQUE ("client_id"), CONSTRAINT "PK_e6ba3f6fd0a8592e4ba27b6044d" PRIMARY KEY ("id")); COMMENT ON COLUMN "client_configurations"."import_mapping" IS 'Custom mapping of Excel columns to FAPOMS schema fields'; COMMENT ON COLUMN "client_configurations"."working_days" IS 'List of working days (0=Sunday, 1=Monday, ..., 6=Saturday)'; COMMENT ON COLUMN "client_configurations"."default_radius" IS 'Default assignment search radius in kilometers'; COMMENT ON COLUMN "client_configurations"."sla_rules" IS 'SLA parameters such as maximum response time, scheduling windows'`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "revoked_at" TIMESTAMP WITH TIME ZONE, "replaced_by" uuid, "ip_address" character varying(50), "user_agent" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba3bd69c8ad1e799c0256e9e50" ON "refresh_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "audit_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying(50) NOT NULL, "event_type" character varying(100) NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" uuid NOT NULL, "previous_state" character varying(50), "new_state" character varying(50), "user_id" uuid, "user_display_name" character varying(200), "ip_address" character varying(50), "remarks" text, "metadata" jsonb, "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_910f64d901a5c3e9878f0d4a407" PRIMARY KEY ("id")); COMMENT ON COLUMN "audit_events"."category" IS 'Event category: OPERATIONAL, USER, WORKFLOW, SYSTEM'; COMMENT ON COLUMN "audit_events"."event_type" IS 'Specific event type, e.g. ASSIGNMENT_ACCEPTED, PROJECT_CREATED'; COMMENT ON COLUMN "audit_events"."entity_type" IS 'Type of entity this event relates to, e.g. PROJECT, ASSIGNMENT'; COMMENT ON COLUMN "audit_events"."entity_id" IS 'ID of the entity this event relates to'; COMMENT ON COLUMN "audit_events"."user_id" IS 'User who triggered the event (null for system events)'; COMMENT ON COLUMN "audit_events"."metadata" IS 'Additional structured data about the event'`);
        await queryRunner.query(`CREATE INDEX "IDX_db2468e1574cba4f38f44083d1" ON "audit_events" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1c246079d669576b847df55d9" ON "audit_events" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e139cc590fd5127ecc451472e" ON "audit_events" ("occurred_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c7623cfe8d008e1c1fd758fbc" ON "audit_events" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TABLE "geo_states" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "name" character varying(100) NOT NULL, "code" character varying(10) NOT NULL, CONSTRAINT "UQ_43835a378d8336cd6817539f050" UNIQUE ("name"), CONSTRAINT "UQ_1052a8dd51ed7ea3757e2309902" UNIQUE ("code"), CONSTRAINT "PK_8c288a05c0fac441b23ad684661" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "geo_districts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "name" character varying(100) NOT NULL, "state_id" uuid NOT NULL, CONSTRAINT "PK_ba73ad56ed2790fea574ae8a3fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_00425d099a7654c37e7faffff0" ON "geo_districts" ("state_id") `);
        await queryRunner.query(`CREATE TABLE "geo_cities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "name" character varying(100) NOT NULL, "district_id" uuid NOT NULL, "pincode" character varying(10), CONSTRAINT "PK_b4abb9549192a64532b3842d539" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c794a324eee38eb5b63a2fbe34" ON "geo_cities" ("district_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "zones" ADD CONSTRAINT "FK_fe93525d97616feb04ceec87658" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_181a8cdaff4e1db94ff147163e2" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_66969a729f0c24ff71d5ba18c43" FOREIGN KEY ("project_branch_id") REFERENCES "project_branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_18b8aab3ad95fc3377bb9986882" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_ce6fc1fcaf3f268efa288ff5a7a" FOREIGN KEY ("assayer_id") REFERENCES "assayers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_branches" ADD CONSTRAINT "FK_55cbe3e92921e38a60ccc2926e2" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_branches" ADD CONSTRAINT "FK_d893541df1e35cef989cc4bed99" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_ca29f959102228649e714827478" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_configurations" ADD CONSTRAINT "FK_8997ef77f905e17348c021608fc" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "geo_districts" ADD CONSTRAINT "FK_00425d099a7654c37e7faffff02" FOREIGN KEY ("state_id") REFERENCES "geo_states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "geo_cities" ADD CONSTRAINT "FK_c794a324eee38eb5b63a2fbe344" FOREIGN KEY ("district_id") REFERENCES "geo_districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "geo_cities" DROP CONSTRAINT "FK_c794a324eee38eb5b63a2fbe344"`);
        await queryRunner.query(`ALTER TABLE "geo_districts" DROP CONSTRAINT "FK_00425d099a7654c37e7faffff02"`);
        await queryRunner.query(`ALTER TABLE "client_configurations" DROP CONSTRAINT "FK_8997ef77f905e17348c021608fc"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_ca29f959102228649e714827478"`);
        await queryRunner.query(`ALTER TABLE "project_branches" DROP CONSTRAINT "FK_d893541df1e35cef989cc4bed99"`);
        await queryRunner.query(`ALTER TABLE "project_branches" DROP CONSTRAINT "FK_55cbe3e92921e38a60ccc2926e2"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_ce6fc1fcaf3f268efa288ff5a7a"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_18b8aab3ad95fc3377bb9986882"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_66969a729f0c24ff71d5ba18c43"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_181a8cdaff4e1db94ff147163e2"`);
        await queryRunner.query(`ALTER TABLE "zones" DROP CONSTRAINT "FK_fe93525d97616feb04ceec87658"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c794a324eee38eb5b63a2fbe34"`);
        await queryRunner.query(`DROP TABLE "geo_cities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00425d099a7654c37e7faffff0"`);
        await queryRunner.query(`DROP TABLE "geo_districts"`);
        await queryRunner.query(`DROP TABLE "geo_states"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c7623cfe8d008e1c1fd758fbc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e139cc590fd5127ecc451472e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1c246079d669576b847df55d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db2468e1574cba4f38f44083d1"`);
        await queryRunner.query(`DROP TABLE "audit_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba3bd69c8ad1e799c0256e9e50"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "client_configurations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40dfddee0c0d7125c767d8962b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c166450c737779ebaab2bf408"`);
        await queryRunner.query(`DROP TABLE "holidays"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a77b19582f25838ea68bbd4ffd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca29f959102228649e71482747"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55cbe3e92921e38a60ccc2926e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d893541df1e35cef989cc4bed9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e536b9d53cc6c920bdbcb94d06"`);
        await queryRunner.query(`DROP TABLE "project_branches"`);
        await queryRunner.query(`DROP TYPE "public"."project_branches_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."project_branches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c08693fc11883cd6b712a1fed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66969a729f0c24ff71d5ba18c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18b8aab3ad95fc3377bb998688"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce6fc1fcaf3f268efa288ff5a7"`);
        await queryRunner.query(`DROP TABLE "assignments"`);
        await queryRunner.query(`DROP TYPE "public"."assignments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac38fe8dfe44eb1ad3310e29fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_719f463c7996b212e17d1dbe65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0dff65957a13ec73746787b645"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12a47006c59a934a43a18565e"`);
        await queryRunner.query(`DROP TABLE "assayers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b48a680eb17f642cc36ff78d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed88203149dc0c61c57fc27da5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_181a8cdaff4e1db94ff147163e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42d97150eb00982d34c088749b"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d577922d963695c90b61c67f3d"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe93525d97616feb04ceec8765"`);
        await queryRunner.query(`DROP TABLE "zones"`);
        await queryRunner.query(`DROP TABLE "clients"`);
    }

}
