import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProjectOperationalFields1784691660986 implements MigrationInterface {
    name = 'AddProjectOperationalFields1784691660986'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_56db59155836a7548efa3272d5d"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_585c8ce06628c70b70100bfb842"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_9ecf73d5ca57108dc33c87f7d88"`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP CONSTRAINT "FK_ef49ab6a9dadb489ce0196237bf"`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP CONSTRAINT "FK_d3ebee0f092c731a50fc43199e0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_21a659804ed7bf61eb91688dea7"`);
        await queryRunner.query(`ALTER TABLE "assayer_documents" DROP CONSTRAINT "FK_4429e2d6dfa476e1171b6825247"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CLIENTS_ORGANIZATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROJECTS_ORGANIZATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BRANCHES_ORGANIZATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSAYERS_ORGANIZATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSAYERS_MANAGER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_ORGANIZATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORGANIZATIONS_CODE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSAYER_REMARKS_ASSAYER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSAYER_REMARKS_CATEGORY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GOV_DOC_ASSAYER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GOV_DOC_TYPE_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSAYER_DOCS_ASSAYER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSAYER_ACTIVITIES_ASSAYER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ASSAYER_ACTIVITIES_OCCURRED"`);
        await queryRunner.query(`CREATE TABLE "capabilities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "name" character varying(100) NOT NULL, "display_name" character varying(100) NOT NULL, "description" text, "category" character varying(50), CONSTRAINT "UQ_87bf22fad6cc44a310239c17f63" UNIQUE ("name"), CONSTRAINT "PK_c94fe6cafdb7646522a915893fd" PRIMARY KEY ("id")); COMMENT ON COLUMN "capabilities"."category" IS 'Logical grouping, e.g. PROJECT, ASSIGNMENT'`);
        await queryRunner.query(`CREATE TABLE "responsibilities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "name" character varying(100) NOT NULL, "display_name" character varying(100) NOT NULL, "description" text, CONSTRAINT "UQ_f45353b6f25f81bea6ad271f85a" UNIQUE ("name"), CONSTRAINT "PK_e22aa58654a4ecfe29d882b85eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_contracts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "client_id" uuid NOT NULL, "contract_number" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "description" text, "signed_date" date, "effective_from" date NOT NULL, "effective_to" date, "value" numeric(14,2), "currency" character varying(3) NOT NULL DEFAULT 'INR', "status" character varying(50) NOT NULL DEFAULT 'DRAFT', "terms" jsonb, "document_url" character varying(500), CONSTRAINT "UQ_2f460572acbe646d21ba615cb0b" UNIQUE ("contract_number"), CONSTRAINT "PK_2b2c5b5b5ea51db7bd615d61c3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b887356704b214c8c27a424f8c" ON "client_contracts" ("client_id") `);
        await queryRunner.query(`CREATE TABLE "client_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "client_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "designation" character varying(200) NOT NULL, "department" character varying(200), "is_primary" boolean NOT NULL DEFAULT false, "notes" text, CONSTRAINT "PK_1d0ab11dc872cb18d4850c970a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ef47f3aae4b36f0aaedbfc0416" ON "client_contacts" ("client_id") `);
        await queryRunner.query(`CREATE TABLE "client_billing" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "client_id" uuid NOT NULL, "payment_terms" character varying(200) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'INR', "tax_identifier" character varying(100), "invoice_cycle" character varying(50) NOT NULL, "billing_address" text NOT NULL, "bank_account" character varying(50), "bank_name" character varying(200), "ifsc_code" character varying(20), "notes" text, CONSTRAINT "UQ_1b6a53cf635ea9e3e9327442a13" UNIQUE ("client_id"), CONSTRAINT "REL_1b6a53cf635ea9e3e9327442a1" UNIQUE ("client_id"), CONSTRAINT "PK_78d5a2fa2971bd764ae4a0ae55f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branch_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "branch_id" uuid NOT NULL, "file_name" character varying(255) NOT NULL, "file_path" text NOT NULL, "file_size" integer NOT NULL, "mime_type" character varying(100), "category" character varying(50) NOT NULL, "remarks" text, CONSTRAINT "PK_ca59f6d5e330a5882c270716f39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_185983b933c14a781d441cb3ac" ON "branch_documents" ("branch_id") `);
        await queryRunner.query(`CREATE TABLE "branch_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "branch_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "designation" character varying(200) NOT NULL, "department" character varying(200), "is_primary" boolean NOT NULL DEFAULT false, "notes" text, CONSTRAINT "PK_fc86de9a802aece781d6ff85ca3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_daf1f626f9f30ced8991cdc179" ON "branch_contacts" ("branch_id") `);
        await queryRunner.query(`CREATE TABLE "capability_permissions" ("capability_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_5c9c9dbcd3586012abeed7587ba" PRIMARY KEY ("capability_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_817a16e738499eea4b9805c535" ON "capability_permissions" ("capability_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cff1b5aaef83a219dd4bb7d6a" ON "capability_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "responsibility_capabilities" ("responsibility_id" uuid NOT NULL, "capability_id" uuid NOT NULL, CONSTRAINT "PK_e980b65062a6816939142274671" PRIMARY KEY ("responsibility_id", "capability_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_be848e2770b2ca06dbe008366a" ON "responsibility_capabilities" ("responsibility_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a34540305eda79ea4b512da51b" ON "responsibility_capabilities" ("capability_id") `);
        await queryRunner.query(`CREATE TABLE "role_responsibilities" ("role_id" uuid NOT NULL, "responsibility_id" uuid NOT NULL, CONSTRAINT "PK_4bdf72468904c6ec9de01bee365" PRIMARY KEY ("role_id", "responsibility_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82e3f80ec1ce0a8e2d9d70b189" ON "role_responsibilities" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b01c9df6d8b4ac90ee21fc8d3" ON "role_responsibilities" ("responsibility_id") `);
        await queryRunner.query(`ALTER TABLE "clients" ADD "website" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "industry" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "client_type" character varying(50) NOT NULL DEFAULT 'OTHER'`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "registration_number" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "tax_id" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "lifecycle_status" character varying(50) NOT NULL DEFAULT 'PROSPECT'`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "budget" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "scope" text`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "required_skills" jsonb`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "required_certifications" jsonb`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "sla" jsonb`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "risks" jsonb`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "milestones" jsonb`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "dependencies" jsonb`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "region" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "territory" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "zone_id" uuid`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "branch_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "manager_name" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "opening_date" date`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "last_audit_date" date`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "operating_hours" jsonb`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "risk_category" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department_id" uuid`);
        await queryRunner.query(`ALTER TABLE "client_configurations" ADD "service_level" character varying(50)`);
        await queryRunner.query(`COMMENT ON COLUMN "client_configurations"."service_level" IS 'SLA tier: PREMIUM, STANDARD, BASIC'`);
        await queryRunner.query(`ALTER TABLE "client_configurations" ADD "max_response_time_hours" integer`);
        await queryRunner.query(`COMMENT ON COLUMN "client_configurations"."max_response_time_hours" IS 'Maximum response time in hours'`);
        await queryRunner.query(`ALTER TABLE "client_configurations" ADD "penalty_rate" numeric(5,2)`);
        await queryRunner.query(`COMMENT ON COLUMN "client_configurations"."penalty_rate" IS 'Penalty rate for SLA breaches (%)'`);
        await queryRunner.query(`ALTER TABLE "client_configurations" ADD "service_hours" jsonb`);
        await queryRunner.query(`COMMENT ON COLUMN "client_configurations"."service_hours" IS 'Service hours configuration'`);
        await queryRunner.query(`ALTER TABLE "assayer_activities" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "employee_id"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "employee_id" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD CONSTRAINT "UQ_40271cf4d07407f77527423f86f" UNIQUE ("employee_id")`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "employee_code"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "employee_code" character varying(50)`);
        await queryRunner.query(`COMMENT ON COLUMN "assayers"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "assayers" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "joining_date"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "joining_date" date`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "exit_date"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "exit_date" date`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "termination_date"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "termination_date" date`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "emergency_contact_name"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "emergency_contact_name" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "emergency_contact_relation"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "emergency_contact_relation" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "photograph"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "photograph" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "UQ_7e27c3b62c681fbe3e2322535f2" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" DROP COLUMN "author_id"`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ADD "author_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ALTER COLUMN "author_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ADD "category" character varying(50) NOT NULL DEFAULT 'GENERAL'`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ALTER COLUMN "visibility" SET DEFAULT 'PUBLIC'`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" DROP COLUMN "document_type"`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ADD "document_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" DROP COLUMN "expiry_date"`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ADD "expiry_date" date`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" DROP COLUMN "verification_status"`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ADD "verification_status" character varying(20) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" DROP COLUMN "verified_by"`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ADD "verified_by" uuid`);
        await queryRunner.query(`ALTER TABLE "assayer_documents" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "assayer_documents" DROP COLUMN "document_type"`);
        await queryRunner.query(`ALTER TABLE "assayer_documents" ADD "document_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_activities" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "assayer_activities" DROP COLUMN "performed_by"`);
        await queryRunner.query(`ALTER TABLE "assayer_activities" ADD "performed_by" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_df27f46f3230f2a790d405536e" ON "branches" ("zone_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ebaccbd26bb5f330e0d550ee7" ON "branches" ("region") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef49ab6a9dadb489ce0196237b" ON "assayers" ("manager_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3ebee0f092c731a50fc43199e" ON "assayers" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa579396537ad5dae151616061" ON "assayers" ("lifecycle_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_40271cf4d07407f77527423f86" ON "assayers" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2784fd924995f8b808f6a250a9" ON "assayer_remarks" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f130019c97be751122b72c380" ON "assayer_remarks" ("assayer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4abd688ca03553f70263ed55a5" ON "assayer_government_documents" ("verification_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_64410ab5b4fff05a986e08519d" ON "assayer_government_documents" ("document_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_80bb365b49abf378830ead6d22" ON "assayer_government_documents" ("assayer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e55231d765a247df2ff9a2644b" ON "assayer_documents" ("document_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac29f62dfb2ca8c62b241b641c" ON "assayer_documents" ("assayer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4868c3ef09a06c4a7295b1684" ON "assayer_activities" ("occurred_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_51c604e01dda8b8b509e5ab18d" ON "assayer_activities" ("assayer_id") `);
        await queryRunner.query(`ALTER TABLE "client_contracts" ADD CONSTRAINT "FK_b887356704b214c8c27a424f8cb" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ADD CONSTRAINT "FK_ef47f3aae4b36f0aaedbfc04161" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_billing" ADD CONSTRAINT "FK_1b6a53cf635ea9e3e9327442a13" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_documents" ADD CONSTRAINT "FK_185983b933c14a781d441cb3acc" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_contacts" ADD CONSTRAINT "FK_daf1f626f9f30ced8991cdc179d" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "capability_permissions" ADD CONSTRAINT "FK_817a16e738499eea4b9805c535f" FOREIGN KEY ("capability_id") REFERENCES "capabilities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "capability_permissions" ADD CONSTRAINT "FK_9cff1b5aaef83a219dd4bb7d6a0" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "responsibility_capabilities" ADD CONSTRAINT "FK_be848e2770b2ca06dbe008366a5" FOREIGN KEY ("responsibility_id") REFERENCES "responsibilities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "responsibility_capabilities" ADD CONSTRAINT "FK_a34540305eda79ea4b512da51be" FOREIGN KEY ("capability_id") REFERENCES "capabilities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_responsibilities" ADD CONSTRAINT "FK_82e3f80ec1ce0a8e2d9d70b189a" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_responsibilities" ADD CONSTRAINT "FK_7b01c9df6d8b4ac90ee21fc8d3c" FOREIGN KEY ("responsibility_id") REFERENCES "responsibilities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_responsibilities" DROP CONSTRAINT "FK_7b01c9df6d8b4ac90ee21fc8d3c"`);
        await queryRunner.query(`ALTER TABLE "role_responsibilities" DROP CONSTRAINT "FK_82e3f80ec1ce0a8e2d9d70b189a"`);
        await queryRunner.query(`ALTER TABLE "responsibility_capabilities" DROP CONSTRAINT "FK_a34540305eda79ea4b512da51be"`);
        await queryRunner.query(`ALTER TABLE "responsibility_capabilities" DROP CONSTRAINT "FK_be848e2770b2ca06dbe008366a5"`);
        await queryRunner.query(`ALTER TABLE "capability_permissions" DROP CONSTRAINT "FK_9cff1b5aaef83a219dd4bb7d6a0"`);
        await queryRunner.query(`ALTER TABLE "capability_permissions" DROP CONSTRAINT "FK_817a16e738499eea4b9805c535f"`);
        await queryRunner.query(`ALTER TABLE "branch_contacts" DROP CONSTRAINT "FK_daf1f626f9f30ced8991cdc179d"`);
        await queryRunner.query(`ALTER TABLE "branch_documents" DROP CONSTRAINT "FK_185983b933c14a781d441cb3acc"`);
        await queryRunner.query(`ALTER TABLE "client_billing" DROP CONSTRAINT "FK_1b6a53cf635ea9e3e9327442a13"`);
        await queryRunner.query(`ALTER TABLE "client_contacts" DROP CONSTRAINT "FK_ef47f3aae4b36f0aaedbfc04161"`);
        await queryRunner.query(`ALTER TABLE "client_contracts" DROP CONSTRAINT "FK_b887356704b214c8c27a424f8cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51c604e01dda8b8b509e5ab18d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4868c3ef09a06c4a7295b1684"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac29f62dfb2ca8c62b241b641c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e55231d765a247df2ff9a2644b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80bb365b49abf378830ead6d22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64410ab5b4fff05a986e08519d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4abd688ca03553f70263ed55a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f130019c97be751122b72c380"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2784fd924995f8b808f6a250a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40271cf4d07407f77527423f86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa579396537ad5dae151616061"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3ebee0f092c731a50fc43199e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef49ab6a9dadb489ce0196237b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ebaccbd26bb5f330e0d550ee7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df27f46f3230f2a790d405536e"`);
        await queryRunner.query(`ALTER TABLE "assayer_activities" DROP COLUMN "performed_by"`);
        await queryRunner.query(`ALTER TABLE "assayer_activities" ADD "performed_by" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_activities" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "assayer_documents" DROP COLUMN "document_type"`);
        await queryRunner.query(`ALTER TABLE "assayer_documents" ADD "document_type" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_documents" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" DROP COLUMN "verified_by"`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ADD "verified_by" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" DROP COLUMN "verification_status"`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ADD "verification_status" character varying(50) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" DROP COLUMN "expiry_date"`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ADD "expiry_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" DROP COLUMN "document_type"`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ADD "document_type" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_government_documents" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ALTER COLUMN "visibility" SET DEFAULT 'INTERNAL'`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ADD "category" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ALTER COLUMN "author_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" DROP COLUMN "author_id"`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ADD "author_id" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assayer_remarks" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "UQ_7e27c3b62c681fbe3e2322535f2"`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "photograph"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "photograph" text`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "emergency_contact_relation"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "emergency_contact_relation" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "emergency_contact_name"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "emergency_contact_name" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "termination_date"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "termination_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "exit_date"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "exit_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "joining_date"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "joining_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assayers" ALTER COLUMN "status" SET DEFAULT 'REGISTERED'`);
        await queryRunner.query(`COMMENT ON COLUMN "assayers"."status" IS 'Assayer status: REGISTERED, ACTIVE, INACTIVE, BUSY, SUSPENDED'`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "employee_code"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "employee_code" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP CONSTRAINT "UQ_40271cf4d07407f77527423f86f"`);
        await queryRunner.query(`ALTER TABLE "assayers" DROP COLUMN "employee_id"`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD "employee_id" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "assayer_activities" DROP COLUMN "metadata"`);
        await queryRunner.query(`COMMENT ON COLUMN "client_configurations"."service_hours" IS 'Service hours configuration'`);
        await queryRunner.query(`ALTER TABLE "client_configurations" DROP COLUMN "service_hours"`);
        await queryRunner.query(`COMMENT ON COLUMN "client_configurations"."penalty_rate" IS 'Penalty rate for SLA breaches (%)'`);
        await queryRunner.query(`ALTER TABLE "client_configurations" DROP COLUMN "penalty_rate"`);
        await queryRunner.query(`COMMENT ON COLUMN "client_configurations"."max_response_time_hours" IS 'Maximum response time in hours'`);
        await queryRunner.query(`ALTER TABLE "client_configurations" DROP COLUMN "max_response_time_hours"`);
        await queryRunner.query(`COMMENT ON COLUMN "client_configurations"."service_level" IS 'SLA tier: PREMIUM, STANDARD, BASIC'`);
        await queryRunner.query(`ALTER TABLE "client_configurations" DROP COLUMN "service_level"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "risk_category"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "operating_hours"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "last_audit_date"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "opening_date"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "manager_name"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "branch_type"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "zone_id"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "territory"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "region"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "dependencies"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "milestones"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "risks"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "sla"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "required_certifications"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "required_skills"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "scope"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "budget"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "lifecycle_status"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "tax_id"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "registration_number"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "client_type"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "industry"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "website"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b01c9df6d8b4ac90ee21fc8d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82e3f80ec1ce0a8e2d9d70b189"`);
        await queryRunner.query(`DROP TABLE "role_responsibilities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a34540305eda79ea4b512da51b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be848e2770b2ca06dbe008366a"`);
        await queryRunner.query(`DROP TABLE "responsibility_capabilities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cff1b5aaef83a219dd4bb7d6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_817a16e738499eea4b9805c535"`);
        await queryRunner.query(`DROP TABLE "capability_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_daf1f626f9f30ced8991cdc179"`);
        await queryRunner.query(`DROP TABLE "branch_contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_185983b933c14a781d441cb3ac"`);
        await queryRunner.query(`DROP TABLE "branch_documents"`);
        await queryRunner.query(`DROP TABLE "client_billing"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef47f3aae4b36f0aaedbfc0416"`);
        await queryRunner.query(`DROP TABLE "client_contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b887356704b214c8c27a424f8c"`);
        await queryRunner.query(`DROP TABLE "client_contracts"`);
        await queryRunner.query(`DROP TABLE "responsibilities"`);
        await queryRunner.query(`DROP TABLE "capabilities"`);
        await queryRunner.query(`CREATE INDEX "IDX_ASSAYER_ACTIVITIES_OCCURRED" ON "assayer_activities" ("assayer_id", "occurred_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSAYER_ACTIVITIES_ASSAYER" ON "assayer_activities" ("assayer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSAYER_DOCS_ASSAYER" ON "assayer_documents" ("assayer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_GOV_DOC_TYPE_STATUS" ON "assayer_government_documents" ("document_type", "verification_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_GOV_DOC_ASSAYER" ON "assayer_government_documents" ("assayer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSAYER_REMARKS_CATEGORY" ON "assayer_remarks" ("assayer_id", "category") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSAYER_REMARKS_ASSAYER" ON "assayer_remarks" ("assayer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ORGANIZATIONS_CODE" ON "organizations" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_ORGANIZATION" ON "users" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSAYERS_MANAGER" ON "assayers" ("manager_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ASSAYERS_ORGANIZATION" ON "assayers" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_BRANCHES_ORGANIZATION" ON "branches" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROJECTS_ORGANIZATION" ON "projects" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_CLIENTS_ORGANIZATION" ON "clients" ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "assayer_documents" ADD CONSTRAINT "FK_4429e2d6dfa476e1171b6825247" FOREIGN KEY ("parent_document_id") REFERENCES "assayer_documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_21a659804ed7bf61eb91688dea7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD CONSTRAINT "FK_d3ebee0f092c731a50fc43199e0" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assayers" ADD CONSTRAINT "FK_ef49ab6a9dadb489ce0196237bf" FOREIGN KEY ("manager_id") REFERENCES "assayers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_9ecf73d5ca57108dc33c87f7d88" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_585c8ce06628c70b70100bfb842" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_56db59155836a7548efa3272d5d" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
