import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Index hygiene pass — duplicate btrees, an unused GiST, one bloated table, two missing FK
 * indexes.
 *
 * ## Duplicate btrees on `assayers`
 *
 * `IDX_40271cf4d07407f77527423f86` (plain btree on `employee_id`) and
 * `IDX_ac38fe8dfe44eb1ad3310e29fb` (plain btree on `assayer_code`) are each a strict subset of a
 * UNIQUE constraint already covering the same single column
 * (`UQ_40271cf4d07407f77527423f86f`, `UQ_ac38fe8dfe44eb1ad3310e29fb0`). A unique index serves
 * every lookup, sort and equality-filter the plain one would, so the plain copies are pure
 * write-amplification. Confirmed via `pg_indexes` before writing this migration — no other
 * index on either table shares the same column set as anything left standing.
 *
 * ## The plain `gist(location)` on `assayers`
 *
 * `IDX_e12a47006c59a934a43a18565e` is a GiST on the raw `geometry` column, generated by the
 * entity's `@Index({ spatial: true })` decorator. `idx_assayers_location_geography` (from
 * `1790300000000-RestoreScaleIndexes`) is a second, functional GiST on `(location::geography)`.
 * Grepped the whole backend for every spatial predicate touching this column before dropping
 * anything:
 *
 *   - `recommendation.engine.ts`: `ST_DWithin(a.location::geography, ST_SetSRID(...)::geography, $4, false)`
 *   - `command-center.service.ts`: `ORDER BY a.location::geography <-> sites.geog`
 *
 * Both cast to `::geography` before touching the column, so both are served by the functional
 * geography index — neither can use the plain geometry GiST (Postgres does not use a geometry
 * index to plan a geography operator, and vice versa). No other file matches a geometry-typed
 * operator (`&&`, `<->`, `ST_Contains`, `ST_Intersects`, etc.) on `location` without the cast.
 * The plain GiST is therefore dead weight kept alive only by the entity decorator; dropping the
 * index here does not touch the decorator or the column, so nothing about the column's shape
 * changes, only this one redundant index.
 *
 * ## `customer_records`
 *
 * Reported at 0 live rows with ~10 MB of bloat — every row in the table's lifetime was deleted
 * or updated in place and never vacuumed back down. `REINDEX TABLE` rebuilds every index on the
 * table from scratch, which is the direct fix for bloated indexes and requires no DDL to reverse
 * (the index definitions are unchanged, only their physical size).
 *
 * ## Missing FK indexes
 *
 * `assayer_remarks.assignment_id` and `assayer_score_overrides.client_id` both carry a foreign
 * key (`fk_assayer_remarks_assignment`, `FK_score_override_client`) with no index leading with
 * that column — `assayer_score_overrides` has `(assayer_id, client_id)` but nothing keyed on
 * `client_id` alone, so a lookup or cascade keyed only by client still scans the table.
 *
 * Trigram (`gin ... gin_trgm_ops`) indexes are untouched throughout.
 */
export class IndexHygieneCleanup1794600000000 implements MigrationInterface {
  name = 'IndexHygieneCleanup1794600000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── assayers: drop btrees made redundant by their own UNIQUE constraint ──────────────────
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_40271cf4d07407f77527423f86"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_ac38fe8dfe44eb1ad3310e29fb"`);

    // ── assayers: drop the plain geometry GiST; the functional geography GiST serves every
    // spatial predicate actually issued against this column (see class docblock for the grep) ──
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_e12a47006c59a934a43a18565e"`);

    // ── customer_records: rebuild every index to reclaim the 10 MB of bloat over 0 live rows ──
    await queryRunner.query(`REINDEX TABLE "customer_records"`);

    // ── missing FK indexes ─────────────────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_assayer_remarks_assignment_id"
      ON "assayer_remarks" ("assignment_id")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_assayer_score_overrides_client_id"
      ON "assayer_score_overrides" ("client_id")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverse in the opposite order, restoring each index with its original definition/name.
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_assayer_score_overrides_client_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_assayer_remarks_assignment_id"`);

    // REINDEX has no schema to undo — the index definitions never changed, only their size.

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_e12a47006c59a934a43a18565e"
      ON "assayers" USING gist ("location")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_ac38fe8dfe44eb1ad3310e29fb"
      ON "assayers" ("assayer_code")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_40271cf4d07407f77527423f86"
      ON "assayers" ("employee_id")
    `);
  }
}
